pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"

denoising_unet_path: "./pretrained_weights/stage1/denoising_unet.pth"
reference_unet_path: "./pretrained_weights/stage1/reference_unet.pth"
pose_guider_path: "./pretrained_weights/stage1/pose_guider.pth"

inference_config: "./configs/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  "assets/stage1/ref_img1.png":
    - "assets/stage1/pose_img1.png.pose.png"
    - "assets/stage1/pose_img2.png.pose.png"
  "assets/stage1/ref_img2.png":
    - "assets/stage1/pose_img1.png.pose.png"
    - "assets/stage1/pose_img2.png.pose.png"

